### ISSUE TITLE
4 주차 과제 작성하기

### ISSUE THREAD

**Issue by gringrape** [gringrape/codesoom_WIL#3]
# 작업1. reducer.js  TDD 로 구현하기
## 작업 목표
- reducer.js 의 테스트를 추가한다. 

## 작업 방향 
- action.js 는 테스트 없이 추가한다.
- 상태 변화는 타이틀 변화, task 추가, task 삭제의 총 세가지 이다.

### 타이틀 변화
- [x] 타이틀 변화에 대한 테스트를 추가한다 - red
- [x] 타이틀 변화를 구현한다 - green
- [x] action 을 추가한다 - refactor
### task 추가
- [x] task 추가에 대한 테스트를 추가한다.
- [x] task 추가를 구현
- [x] 뭔가 refactor
### task 삭제 추가
- [x] task 삭제에 대한 테스트를 추가한다. 
- [x] task 삭제를 구현한다.
- [x] 뭔가를 리팩토링한다. 

## 회고사항
- BDD 케이스가 너무 복잡해지지 않도록 관리하자. -> 문장을 단순하게 작성하자.
- 리팩토링 시 다른 사람의 리뷰를 참고하자.
- 과제의 의도는 연습이므로 일반적인 케이스에 대해서 먼저 테스트하자.
- 보다 간결하게 테스트 할 수는 없을까?

## 수정사항
- [x] 한줄로 쓸 수 있는 객체는 한 줄로 쓰기
- [x] 하드 코딩 주의, 이전 상태에서 string 가져오기
- [x] 테스트 이름 수정하기

## 질문사항
- validation 을 reducer 에서 진행하여야 할까? 아니라면 어디서 진행하면 좋을까?

**Comment by gringrape** [comment]
# 작업2. reducer 구현하기

**Comment by gringrape** [comment]
# 작업2. App 컴포넌트 TDD 로 구현하기
## 작업 방향
- App 컴포넌트에 통합테스트 추가하기
- store, dispatcher 를 어떻게 도입할지 찾아보기
## 작업계획
### 통합테스트 추가
- [x] user 가 addButton 을 클릭하면, 추가된 테스트가 나타난다.
- [x] user 가 deleteButton 을 클릭하면, 삭제된 테스트가 사라진다.
- [x] user 가 타이틀을 변경하면, input 이 해당 타이틀을 갖게된다. 
### store, dispatcher 를 어떻게 도입할지 찾아보기
App 에서 통합테스트가 완성된 후에 안전하게 테스트를 진행한다.
- [x] reducer 를 분리해낸다
- [x] 상태를 받기 위한 테스트를 작성한다 ---> 이 부분을 외운다.
- [x] redux, react-redux 를 설치한다.
- [x] store 를 분리해낸다.

**Comment by gringrape** [comment]
# 작업 1 상세 - addTask 테스트
## 테스트 케이스
- Given: Reducer, addTask action
Then
- 타이틀을 저장된 스테이트를 사용해서 업데이트 한다.

**Comment by gringrape** [comment]
# 작업 3. App 에서 Container 컴포넌트와 rendering 컴포넌트를 구분하고 구현하기
## 작업방향
- 아샬님 강의로 지식습득
- 강의의 내용을 모델로 만들어서 정리
- 정리된 내용을 보면서 디테일을 재현해내기 
## 작업계획
- [x] 3번째 강의 보기
- [x] 강의 모델 정리
- [x] TDD 구현 순서 결정
## 구현 순서 결정
- [x] ListContainer 테스트
- [x] ListContainer 구현
- [x] InputContainer 테스트
- [x] InputContainer 구현

**Comment by gringrape** [comment]
# 강의 3 내용 정리
## 강의 주제
- App 리팩토링
- Presentational 컴포넌트와 Container 컴포넌트를 구분한다.
## 강의 내용
- App 에서 가지고 있는 상태의 성격이 다르다 -> 둘다 들고 있을 필요가 없다.
- 각각의 컴포넌트에 나누어 주어야 한다. 
- 나누어줄때, 각각의 컴포넌트는 상태를 관리하는 책임(Container) 과 받은것을 그대로 그리는 책임(Present) 로 나눌 수 있다.
